-- +goose Up
ALTER TABLE orders
    DROP COLUMN IF EXISTS user_id,
    DROP COLUMN IF EXISTS updated_at,
    DROP COLUMN IF EXISTS pickup_lat,
    DROP COLUMN IF EXISTS pickup_lon,
    DROP COLUMN IF EXISTS dropout_lat,
    DROP COLUMN IF EXISTS dropout_lon,
    DROP CONSTRAINT IF EXISTS user_id_fk;
-- +goose Down
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS pickup_lat DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pickup_lon DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS dropout_lat DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS dropout_lon DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES users(id);